export const servicePages = {
  "fiber-internet-nairobi": {
    seoTitle: "Fibre & Wi-Fi in Nairobi: Plans & Installation",
    metaDescription: "Compare Shenacha Fiber plans and request a Nairobi coverage check, clean cable trunking, conduit planning or landlord Wi-Fi consultation.",
    eyebrow: "FIBRE & WI-FI IN NAIROBI",
    title: "Fibre internet and Wi-Fi installation for Nairobi properties.",
    description: "Shenacha installs new connections, plans router placement and handles structured cabling, conduit routes and neat trunking where required.",
    service: "internet",
    image: "/images/home-office.jpg",
    imageAlt: "A woman using a laptop in a home office",
    primaryCta: "Check internet coverage",
    secondaryCta: "Compare internet plans",
    summaryTitle: "Plan the connection, cabling and Wi-Fi together.",
    summary: "Router position, walls, floor layout and active users all affect Wi-Fi. Shenacha can connect the premises, structure new cabling through conduits, trunk existing cables for a cleaner finish and advise landlords on the right apartment solution.",
    suitableFor: ["Homes and home offices", "Apartments and landlord projects", "Offices and business premises", "New builds needing structured cabling"],
    outcomes: ["Coverage checked before payment", "Cable route agreed before installation", "Existing cables neatly trunked where requested", "New cabling structured through available conduits", "Key devices tested at handover"],
    scope: ["Installation charge and cable route", "Router and additional Wi-Fi equipment", "Trunking or conduit requirements", "Package terms and Fair Usage Policy", "Support and payment arrangements"],
    process: [
      ["Tell us about the property", "Share the Nairobi area, building, property type and number of users so the team can prepare the right questions."],
      ["Confirm coverage and scope", "Shenacha confirms coverage, equipment, cable routing, trunking or conduit work, installation charges and timing."],
      ["Install and test", "The connection and Wi-Fi are installed, key devices are tested and the support process is explained."],
    ],
    faqs: [
      ["Can I get Shenacha Fiber at my location?", "Coverage varies by area, building and property. Submit the area, apartment or nearest landmark for confirmation."],
      ["Can you tidy cables that are already installed?", "Yes. Shenacha offers cable trunking for existing runs to create a cleaner finish, subject to an on-site assessment."],
      ["Do you structure cables for a new building?", "Yes. Where a new premise has suitable conduits, Shenacha can plan and structure the cable routes before the final Wi-Fi installation."],
      ["Can landlords get help planning apartment Wi-Fi?", "Yes. Shenacha offers consultation for landlords to compare practical Wi-Fi layouts, cable routes and equipment needs for their apartments."],
      ["Which package should I choose?", "The right starting point depends on the number of users and what they do online at the same time. Share those details in the enquiry form for a recommendation."],
    ],
  },
  "cctv-installation-nairobi": {
    seoTitle: "CCTV Installation in Nairobi for Homes & Premises",
    metaDescription: "Request a Nairobi CCTV site survey for a home, office, apartment or other suitable property, with camera placement and recording planned first.",
    eyebrow: "CCTV INSTALLATION IN NAIROBI",
    title: "CCTV installation planned around your property.",
    description: "We assess entrances, compounds, parking areas, lighting and blind spots before recommending camera positions, recording and remote viewing.",
    service: "cctv",
    image: "/images/cctv-installation.jpg",
    imageAlt: "A technician installing a security camera outside a building",
    primaryCta: "Request a CCTV site survey",
    secondaryCta: "Ask a CCTV question",
    summaryTitle: "Start with the property, not a camera bundle.",
    summary: "A useful CCTV system depends on placement, lighting, viewing angle, recording requirements and the spaces you want to protect. A site discussion determines the practical camera count and cable routes before equipment is quoted.",
    suitableFor: ["Homes and compounds", "Apartments and shared areas", "Offices and business premises", "Shops and commercial premises"],
    outcomes: ["Camera positions agreed after a walk-through", "Cable routes and recording requirements scoped", "Remote viewing configured where supported", "Day and night views tested at handover", "Responsible users shown how to review footage"],
    scope: ["Camera count and position", "Cable routes and available power", "Recording equipment and expected retention", "Monitor or remote-viewing setup", "Installation timing and maintenance options"],
    process: [["Discuss the property", "Share the property type, Nairobi area and the spaces you want to monitor."], ["Walk through and scope", "Confirm entrances, priority views, blind spots, lighting, cable routes and available power."], ["Install and hand over", "Test important views, recording and supported remote access with the responsible person."]],
    faqs: [["How many cameras will I need?", "The number depends on the property layout and the areas that need coverage. A survey should come before a final recommendation."], ["Can I view the cameras on my phone?", "Remote viewing can be configured where the selected equipment and internet connection support it."], ["Will the cameras work at night?", "Night performance depends on the camera, placement and available lighting. Important views are tested at handover."], ["Can you install at a personal home or office?", "Yes. Shenacha works with homes, offices, apartments and other suitable properties after confirming access and installation requirements."], ["Do you provide maintenance?", "Maintenance and call-out arrangements depend on the final project scope and are confirmed in the quotation."]],
  },
  "biometric-access-control-nairobi": {
    seoTitle: "Biometric Gate & Door Access Control in Nairobi",
    metaDescription: "Plan fingerprint and credential access for suitable gates and doors at Nairobi homes, offices, apartments and other premises.",
    eyebrow: "BIOMETRIC ACCESS IN NAIROBI",
    title: "Biometric access for compatible gates and doors.",
    description: "Shenacha checks the entrance, lock, controller, power and manual override before installing fingerprint or credential access.",
    service: "access",
    image: "/images/biometric-access.jpg",
    imageAlt: "A fingerprint door access system being used",
    primaryCta: "Request an access assessment",
    secondaryCta: "Discuss my gate or door",
    summaryTitle: "Access designed around daily use.",
    summary: "Before installation, we confirm who needs access, who will manage users, what happens during a power interruption and how manual entry will work.",
    suitableFor: ["Homes", "Apartment entrances", "Office and business doors", "Managed residential gates"],
    outcomes: ["Gate or door compatibility checked first", "Power and manual override requirements planned", "User groups and administrator responsibilities agreed", "Authorised users enrolled", "Administrator trained at handover"],
    scope: ["Gate, door and locking compatibility", "Controller and available power", "Backup and manual access", "Number and type of authorised users", "Enrolment, removal and administrator training"],
    process: [["Tell us about the entrance", "Share the property type, Nairobi area, gate or door and estimated number of users."], ["Compatibility check", "Review the entrance, power, locking method and safe override requirements."], ["Configuration and training", "Install the agreed system, enrol authorised users and train the designated administrator."]],
    faqs: [["Can biometric access work with my existing gate?", "It depends on the gate mechanism, controller, locking system and power arrangement. A compatibility check is required first."], ["Can you install at a home, office or apartment?", "Yes, where the gate or door is compatible and the property can support the required power, locking and safe override arrangements."], ["What happens when there is no power?", "The backup and manual-access method is designed for the property and explained before installation."], ["Who can add or remove users?", "A designated administrator is trained to manage authorised users within the selected system."], ["Where is biometric information stored?", "Storage depends on the selected system and configuration. The final scope should explain how templates or access records are stored, accessed and deleted."]],
  },
} as const;

export const legacyServiceRoutes = {
  "fiber-internet-juja": "fiber-internet-nairobi",
  "cctv-installation-juja": "cctv-installation-nairobi",
  "biometric-access-control-juja": "biometric-access-control-nairobi",
} as const;

export type ServicePageSlug = keyof typeof servicePages;
